name: Extract name Reddisekhar 
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Enter namespace'
        required: true
        default: 'None'
        type: choice
        options:
        - 'abc-def-efg-hij'
        - 'jkl-mno-pqr'
        - 'jkl-mno-pqr-test'
        - None
      environment:
        description: 'Enter environment'
        required: true
        default: 'None'
        type: choice
        options:
        - 'UAT1'
        - 'UAT2'
        - None
env:
  PARAMETER_WF: ${{ github.event.inputs.namespace }}      
  TARGET_ENV: ${{ github.event.inputs.environment }}      
jobs:
  extract_age:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Age
      id: read-data
      run: |
        if jq -e ".[] | select(has(\"$PARAMETER_WF\"))" ./${TARGET_ENV}/property.json > /dev/null; then
          name=$(jq ".[] | select(has(\"$PARAMETER_WF\")) | .[\"$PARAMETER_WF\"].name" ./${TARGET_ENV}/property.json)
          version=$(jq ".[] | select(has(\"$PARAMETER_WF\")) | .[\"$PARAMETER_WF\"].version | tonumber" ./${TARGET_ENV}/property.json)
          city=$(jq ".[] | select(has(\"$PARAMETER_WF\")) | .[\"$PARAMETER_WF\"].city" ./${TARGET_ENV}/property.json)
          echo "name=$name" >>"$GITHUB_OUTPUT"
          echo "version=$version" >>"$GITHUB_OUTPUT"
          echo "city=$city" >>"$GITHUB_OUTPUT"
          echo "Name of $PARAMETER_WF is $name"
          echo "version of $PARAMETER_WF is $version"
          echo "city of $PARAMETER_WF is $city"
        else
          echo "$PARAMETER_WF object not found in the JSON file."
        fi
    - name: display in another step
      run: |
        echo "name: ${{ steps.read-data.outputs.name}}"
        echo "version: ${{ steps.read-data.outputs.version}}"
        echo "city: ${{ steps.read-data.outputs.city}}"
