name: Extract and Print Person1 Details

on:
  push:
    branches:
      - main

jobs:
  extract_and_print_person1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Person1 Details
      id: extract_details
      run: |
        person1_details=$(jq '.[] | select(.person1)' data.json)
        name=$(echo "$person1_details" | jq -r '.person1.name')
        age=$(echo "$person1_details" | jq -r '.person1.age')
        city=$(echo "$person1_details" | jq -r '.person1.city')
        #echo "::set-output name=name::$name"
        echo "name=$name" >>"$GITHUB_OUTPUT"
        #echo "::set-output name=age::$age"
        echo "age=$age" >>"$GITHUB_OUTPUT"
        #echo "::set-output name=city::$city"
        echo "city=$city" >>"$GITHUB_OUTPUT"
    

    - name: Print Person1 Details
      run: |
        echo "NAME: ${{ steps.extract_details.outputs.name }}"
        echo "AGE: ${{ steps.extract_details.outputs.age }}"
        echo "CITY: ${{ steps.extract_details.outputs.city }}"
        
    - name: test in another step
      run: |
        echo "$NAME"
        echo "$AGE"
        echo "$CITY"
