name: Extract Age

on:
  push:
    branches:
      - main

jobs:
  extract_age:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Age
      run: |
        if jq -e '.[] | select(.per-son-2)' data.json > /dev/null; then
          AGE=$(jq '.[] | select(.per-son-2) | .per-son-2.age' data.json)
          NAME=$(jq '.[] | select(.per-son-2) | .per-son-2.name' data.json)
          CITY=$(jq '.[] | select(.per-son-2) | .per-son-2.city' data.json)
         
         echo "Age of per-son-2 is $AGE"
         echo "Name of per-son-2 is $NAME"
         echo "Age of per-son-2 is $CITY"
        else
          echo "per-son-2 object not found in the JSON file."
        fi
