name: Extract age
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Enter namespace'
        required: true
        default: 'namespace1'
        type: choice
        options:
        - 'namespace1'
        - 'namespace2'
        - 'namespace3'
        - None
env:
  GKE_NAMESPACE: ${{ github.event.inputs.namespace }}        

jobs:
  extract_age:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Age
      run: |
        if jq -e '.[] | select(${GKE_NAMESPACE})' data.json > /dev/null; then
          AGE=$(jq '.[] | select(${GKE_NAMESPACE}) | ${GKE_NAMESPACE}.age' data.json)
          NAME=$(jq '.[] | select(${GKE_NAMESPACE}) | ${GKE_NAMESPACE}.name' data.json)
          CITY=$(jq '.[] | select(${GKE_NAMESPACE}) | ${GKE_NAMESPACE}.city' data.json)
         
         echo "Age of person1 is $AGE"
         echo "Name of person1 is $NAME"
         echo "Age of person1 is $CITY"
        else
          echo "$GKE_NAMESPACE object not found in the JSON file."
        fi
