name: Deploy

on:
  push:
    branches:
      - main

jobs:

# Do something

  deploy:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@master
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=100" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: 
          echo "The selected color is reddi-$SELECTED_COLOR"
      - name: my-name
        env:
          SELECTED_COLOR1: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: 
          echo "The selected color is sekhar-$SELECTED_COLOR1-Jithu"
          
